title:
logo: /assets/img/logo.png
description: **Keir Hamilton, DPM**, an Experienced Cannabis Consultant, Servicing the SF Bay Area, CA, USA.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
url: https://keirhamilton@github.io/
